name: websafe_platform
description: Simple abstraction to be able to detect Web, Android, and iOS without a hard reference to `dart:io`
version: 1.0.1+1
homepage: https://github.com/peiffer-innovations/websafe_platform

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any
  test_coverage: any

