name: websafe_svg
description: Simple abstraction to be able to use SVGs in Android, iOS, and Web.
version: 2.0.0
homepage: https://github.com/peiffer-innovations/websafe_svg
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  convert: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
