name: websafe_svg
description: Simple abstraction to be able to use SVGs in Android, iOS, and Web.
version: 1.1.3
homepage: https://github.com/peiffer-innovations/websafe_svg
environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^2.1.1
  flutter_svg: ^0.18.1
  http: ^0.12.2
  meta: ^1.2.2
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
