name: websafe_svg
description: Simple abstraction to be able to use SVGs in Android, iOS, and Web.
version: 1.1.4+2
homepage: https://github.com/peiffer-innovations/websafe_svg
environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.2+1
  http: ^0.12.2
  logging: ^0.11.4
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
